services:
  - type: web
    name: zinat-al-khalij-api
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: zinat-al-khalij-db
          property: connectionString

databases:
  - name: zinat-al-khalij-db
